import { chromium } from 'playwright';
const WEB = 'https://poc-mundial.exai.extreme.digital';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1360, height: 860 } });
page.on('console', (m) => console.log('CONSOLE:', m.type(), m.text()));
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message, '\n', e.stack));
page.on('request', (r) => console.log('REQ:', r.method(), r.url()));
page.on('requestfailed', (r) => console.log('REQFAIL:', r.url(), r.failure()?.errorText));
page.on('response', (r) => console.log('RES:', r.status(), r.url()));
await page.goto(`${WEB}/entrar`, { waitUntil: 'load' });
await page.waitForTimeout(2000);
console.log('---- after initial load, before fill ----');
await page.fill('#mat', '04127');
await page.fill('#sen', 'mundial');
console.log('---- filled, clicking ----');
await page.click('button[type=submit]');
await page.waitForTimeout(4000);
console.log('URL after submit:', page.url());
await browser.close();
